In [1]:
import pandas as pd

In [2]:
import requests

In [3]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c8345283069dc12c3e8639a11eace417&language=en-US&page=1')

In [4]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 137.694,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 18307},
  {'adult': False,
   'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 100.272,
   'poster_path': '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 24228},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 68.643,
   'poster_path': '/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 11047},
  {'adult': False,
   'backdrop_path': '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 28.244,
   'poster_path': '/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 4186},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 49.204,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.6,
   'vote_count': 14316},
  {'adult': False,
   'backdrop_path': '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 89.806,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 14606},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 46.106,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 7461},
  {'adult': False,
   'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
   'genre_ids': [10749, 16, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 80.871,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 10077},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 69.239,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 16075},
  {'adult': False,
   'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 107.99,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-14',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 30145},
  {'adult': False,
   'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 66.614,
   'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 15667},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 78.006,
   'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 25531},
  {'adult': False,
   'backdrop_path': '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 69.67,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 25032},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
   'popularity': 92.614,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 21905},
  {'adult': False,
   'backdrop_path': '/eoCSp75lxatmIa6aGqfnzwtbttd.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 70.866,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 7561},
  {'adult': False,
   'backdrop_path': '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
   'genre_ids': [28, 12, 16, 878],
   'id': 569094,
   'original_language': 'en',
   'original_title': 'Spider-Man: Across the Spider-Verse',
   'overview': 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
   'popularity': 1058.671,
   'poster_path': '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
   'release_date': '2023-05-31',
   'title': 'Spider-Man: Across the Spider-Verse',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 2541},
  {'adult': False,
   'backdrop_path': '/ejnlCzBd5pOGAYCpxC93NXSrdrz.jpg',
   'genre_ids': [35, 14],
   'id': 772071,
   'original_language': 'es',
   'original_title': 'Cuando Sea Joven',
   'overview': '70-year-old Malena gets a second chance at life when she magically turns into her 22-year-old self. Now, posing as "Maria" to hide her true identity, she becomes the lead singer of her grandson\'s band and tries to recover her dream of singing, which she had to give up at some point.',
   'popularity': 17.396,
   'poster_path': '/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg',
   'release_date': '2022-09-14',
   'title': 'Cuando Sea Joven',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 249},
  {'adult': False,
   'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 50.389,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 11482},
  {'adult': False,
   'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
   'genre_ids': [18, 10749],
   'id': 11216,
   'original_language': 'it',
   'original_title': 'Nuovo Cinema Paradiso',
   'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
   'popularity': 29.898,
   'poster_path': '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
   'release_date': '1988-11-17',
   'title': 'Cinema Paradiso',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 3844},
  {'adult': False,
   'backdrop_path': '/aVFx1VtlOxR3v0ADEatalXOvwbu.jpg',
   'genre_ids': [16, 14, 28],
   'id': 620249,
   'original_language': 'zh',
   'original_title': '罗小黑战记',
   'overview': "When cat spirit Luo Xiaohei's home is deforested by humans, he must find a new one. He runs into a group of other spirit creatures who take him under their wing with dreams of reconquering the land they say is rightfully theirs. However, they run into a human known as Wuxian who separates Luo Xiaohei from the other spirits and the two go on a journey, with the cat spirit learning to control his abilities as well as forming his own thoughts on whether or not he should ally with the spirits or the humans.",
   'popularity': 11.384,
   'poster_path': '/aLv87NgRJUPkQ6sVLP72IisDdt4.jpg',
   'release_date': '2019-08-27',
   'title': 'The Legend of Hei',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 287}],
 'total_pages': 566,
 'total_results': 11307}

In [5]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",137.694,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.7,18307
1,False,/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg,"[18, 80]",278,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,100.272,/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg,1994-09-23,The Shawshank Redemption,False,8.7,24228
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,68.643,/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg,1974-12-20,The Godfather Part II,False,8.6,11047
3,False,/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",28.244,/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.6,4186
4,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,49.204,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.6,14316
5,False,/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",89.806,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.5,14606
6,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,46.106,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.5,7461
7,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[10749, 16, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,80.871,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.5,10077
8,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",69.239,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.5,16075
9,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,107.990,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-14,The Dark Knight,False,8.5,30145
10,False,/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,66.614,/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg,1999-12-10,The Green Mile,False,8.5,15667
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",78.006,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.5,25531
12,False,/qdIMHd4sEfJSckfVJfKQvisL02a.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,69.670,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.5,25032
13,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,92.614,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.5,21905
14,False,/eoCSp75lxatmIa6aGqfnzwtbttd.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,70.866,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,"The Good, the Bad and the Ugly",False,8.5,7561
15,False,/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg,"[28, 12, 16, 878]",569094,en,Spider-Man: Across the Spider-Verse,"After reuniting with Gwen Stacy, Brooklyn’s fu...",1058.671,/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg,2023-05-31,Spider-Man: Across the Spider-Verse,False,8.5,2541
16,False,/ejnlCzBd5pOGAYCpxC93NXSrdrz.jpg,"[35, 14]",772071,es,Cuando Sea Joven,70-year-old Malena gets a second chance at lif...,17.396,/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg,2022-09-14,Cuando Sea Joven,False,8.5,249
17,False,/sw7mordbZxgITU877yTpZCud90M.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",50.389,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.5,11482
18,False,/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg,"[18, 10749]",11216,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",29.898,/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg,1988-11-17,Cinema Paradiso,False,8.5,3844
19,False,/aVFx1VtlOxR3v0ADEatalXOvwbu.jpg,"[16, 14, 28]",620249,zh,罗小黑战记,When cat spirit Luo Xiaohei's home is deforest...,11.384,/aLv87NgRJUPkQ6sVLP72IisDdt4.jpg,2019-08-27,The Legend of Hei,False,8.5,287

In [6]:
temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','popularity','release_date','vote_average','vote_count']]

In [7]:
temp_df

,id,title,overview,popularity,release_date,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",137.694,1972-03-14,8.7,18307
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,100.272,1994-09-23,8.7,24228
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,68.643,1974-12-20,8.6,11047
3,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",28.244,1995-10-20,8.6,4186
4,424,Schindler's List,The true story of how businessman Oskar Schind...,49.204,1993-12-15,8.6,14316
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",89.806,2001-07-20,8.5,14606
6,389,12 Angry Men,The defense and the prosecution have rested an...,46.106,1957-04-10,8.5,7461
7,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,80.871,2016-08-26,8.5,10077
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",69.239,2019-05-30,8.5,16075
9,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,107.990,2008-07-14,8.5,30145
10,497,The Green Mile,A supernatural tale set on death row in a Sout...,66.614,1999-12-10,8.5,15667
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",78.006,1994-09-10,8.5,25531
12,13,Forrest Gump,A man with a low IQ has accomplished great thi...,69.670,1994-06-23,8.5,25032
13,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,92.614,2003-12-01,8.5,21905
14,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,70.866,1966-12-23,8.5,7561
15,569094,Spider-Man: Across the Spider-Verse,"After reuniting with Gwen Stacy, Brooklyn’s fu...",1058.671,2023-05-31,8.5,2541
16,772071,Cuando Sea Joven,70-year-old Malena gets a second chance at lif...,17.396,2022-09-14,8.5,249
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",50.389,1990-09-12,8.5,11482
18,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",29.898,1988-11-17,8.5,3844
19,620249,The Legend of Hei,When cat spirit Luo Xiaohei's home is deforest...,11.384,2019-08-27,8.5,287

In [8]:
df = pd.DataFrame()

In [9]:
df

Empty DataFrame
Columns: []
Index: []

In [12]:
for i in range(1,565):
    response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c8345283069dc12c3e8639a11eace417&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','popularity','release_date','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

KeyError: 'results'

In [13]:
df

,id,title,overview,popularity,release_date,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",137.694,1972-03-14,8.7,18307
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,100.272,1994-09-23,8.7,24228
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,68.643,1974-12-20,8.6,11047
3,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",28.244,1995-10-20,8.6,4186
4,424,Schindler's List,The true story of how businessman Oskar Schind...,49.204,1993-12-15,8.6,14316
...,...,...,...,...,...,...,...
19995,23398,Alvin and the Chipmunks: The Squeakquel,"Pop sensations Alvin, Simon and Theodore end u...",43.352,2009-12-21,5.6,2651
19996,20777,The Killing Room,Four volunteers sign up for what initially app...,7.677,2009-01-16,5.6,218
19997,11888,Snow Dogs,When a Miami dentist inherits a team of sled d...,14.505,2002-01-18,5.6,666
19998,735595,The Scary House,"When a big-city family moves to a remote town,...",11.883,2020-10-30,5.6,212
19999,74461,Knights of Badassdom,Three best friends and dedicated roleplayers t...,10.282,2013-01-21,5.6,362

In [15]:
df.shape

(20000, 7)

In [18]:
df.to_csv('movies.csv')

In [21]:
df.sort_values('release_date', ascending=False)

,id,title,overview,popularity,release_date,vote_average,vote_count
50,872585,Oppenheimer,The story of J. Robert Oppenheimer’s role in t...,1155.971,2023-07-19,8.4,999
1206,346698,Barbie,Barbie and Ken are having the time of their li...,4493.487,2023-07-19,7.6,1621
10050,872585,Oppenheimer,The story of J. Robert Oppenheimer’s role in t...,1155.971,2023-07-19,8.4,999
11206,346698,Barbie,Barbie and Ken are having the time of their li...,4493.487,2023-07-19,7.6,1621
7910,805320,Bird Box Barcelona,After a mysterious force decimates the world’s...,722.300,2023-07-14,6.2,338
...,...,...,...,...,...,...,...
3470,5698,The Great Train Robbery,After the train station clerk is assaulted and...,8.233,1903-12-07,7.0,536
383,775,A Trip to the Moon,Professor Barbenfouillis and five of his colle...,17.585,1902-04-17,8.0,1544
10383,775,A Trip to the Moon,Professor Barbenfouillis and five of his colle...,17.585,1902-04-17,8.0,1544
14086,82120,The Sprinkler Sprinkled,"A gardener is watering his flowers, when a mis...",5.692,1895-06-10,6.9,219
4086,82120,The Sprinkler Sprinkled,"A gardener is watering his flowers, when a mis...",5.692,1895-06-10,6.9,219

In [22]:
df.sort_values('vote_average', ascending=False).head

,id,title,overview,popularity,release_date,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",137.694,1972-03-14,8.7,18307
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,100.272,1994-09-23,8.7,24228
10001,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,100.272,1994-09-23,8.7,24228
10000,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",137.694,1972-03-14,8.7,18307
4,424,Schindler's List,The true story of how businessman Oskar Schind...,49.204,1993-12-15,8.6,14316
...,...,...,...,...,...,...,...
9982,11569,Hellraiser III: Hell on Earth,Pinhead is trapped in the Pillar of Souls. For...,15.100,1992-09-11,5.6,644
9981,244516,Indovina chi viene a Natale?,A very extended family gathers for the Christm...,4.722,2013-12-19,5.6,338
9980,8277,American Pie Presents: Beta House,"Erik, Ryan, and Cooze start college and pledge...",54.011,2007-12-26,5.6,1727
9979,24271,The Maiden Heist,A comedy centered on three museum security gua...,12.548,2009-05-09,5.6,289
19999,74461,Knights of Badassdom,Three best friends and dedicated roleplayers t...,10.282,2013-01-21,5.6,362